---
title: "Join the lab"
---

### [URECA/FYP students]{.underline}

If you are thinking about doing your FYP/URECA project under my supervision, here are some things to take note:

Throughout your FYP/URECA project, you do not need to collect the data on your own, and you do not have to apply for ethics review. All the data you need for your FYP has already been collected— I have got a large database of neuropsychological, psychiatric and neuroimaging data from many healthy subjects, and clinical populations (e.g., mild cognitive impairment, Alzheimer’s disease, schizophrenia, bipolar, ADHD, substance abuse). You can take your time to explore the different datasets to decide how you want to conceive your study. 

The cons— the learning curve can be quite steep—you will need to learn to work with neuroimaging data using R or even a linux command line environment. Nevertheless I’ve prepared a lot of learning resources— lectures, worked examples which you can view at your own time. It will be helpful to have some previous coding experience (e.g., R, Matlab, Python), but this is not a strict requirement. Regardless of your level of experience in neuroimaging analyses, it is of utmost importance to have an open and inquisitive mind to learn new things—and on your own if necessary.

While pursuing a neuroimaging research project may seem somewhat challenging, I have had URECA students who started out with very little or no prior experience in neuroimaging analyses; despite this, they still managed to complete impressive research projects using brain connectivity data. In fact, their research have been accepted for oral presentations at major international psychology/neuroscience conferences.

Since you do not have to do any data collection or submit an ethics review application (unlike other students), I will need you spend the time that you would otherwise use to collect the data or work on an ethics application to help out in the recruitment and data collection of one of my ongoing research projects. This will probably take up 1-2 hours/week of your time. On some of your busier weeks (i.e., mid-terms/exams), I can excuse your absence, but overall, I expect you to actively participate, contribute and learn from one another within the lab.

### [M.A./PhD positions — January/August intake]{.underline}

Contact me (junhong.yu\@ntu.edu.sg) to discuss. More information regarding the M.A. /PhD programme at NTU psychology is available [here](https://www.ntu.edu.sg/sss/graduate-education/graduate-research/psychology)
